### ISSUE TITLE
RTL theme tweaks

### ISSUE THREAD

**Issue by Exlord** [wbb/WysiBB#73]
theme css required for the rtl theme :

``` css
.wysibb .wysibb-toolbar .modeSwitch{ right:auto; left:0; }
.wysibb .wysibb-toolbar{ padding:0 0 0 60px; }
.wbb-select .val{ margin-right:0; margin-left:10px; }
.wysibb .wysibb-toolbar .wysibb-toolbar-container .wysibb-toolbar-btn.wbb-select .sar{ right:auto; left:3px; }
.wysibb .wysibb-toolbar .wysibb-toolbar-container .wysibb-toolbar-btn.wbb-select,
.wysibb .wysibb-toolbar .wysibb-toolbar-container .wysibb-toolbar-btn.wbb-select.dis:hover,
.wysibb .wysibb-toolbar .wysibb-toolbar-container .wysibb-toolbar-btn.wbb-select:active{ padding:1px 5px 1px 1px; }
.wysibb .wysibb-toolbar .wysibb-toolbar-container .wysibb-toolbar-btn span.btn-tooltip{ left:auto; right:0; }
.wysibb .wysibb-toolbar .wysibb-toolbar-container .wysibb-toolbar-btn span.btn-tooltip ins{ left:auto; right:3px; }
.wysibb .wysibb-toolbar .wysibb-toolbar-container .wysibb-toolbar-btn .wbb-list{ left:auto; right:-1px; }
```
